const CATS = [
  {id:'NVV',                     de:'Nomen-Verb-Verbindungen', en:'NVV',                         uk:'NVV',                  e:'🧩'},
  {id:'Soft Skills',             de:'Soft Skills',             en:'Soft Skills',                 uk:'Soft Skills',          e:'🧠'},
  {id:'Hard Skills',             de:'Hard Skills',             en:'Hard Skills',                 uk:'Hard Skills',          e:'💻'},
  {id:'Mein Beruf',              de:'Mein Beruf',              en:'My profession',               uk:'Моя професія',         e:'💼'},
  {id:'Zusammenarbeit',          de:'Zusammenarbeit',          en:'Zusammenarbeit',              uk:'Zusammenarbeit',       e:'🤝'},
  {id:'Mein Weg in den Beruf',   de:'Mein Weg in den Beruf',   en:'My way in profession',        uk:'Мій шлях  професії',  e:'🚀'},
  {id:'Der erste Arbeitstag',    de:'Der erste Arbeitstag',    en:'The First Day of Work',       uk:'Перший робочий день',  e:'✨'},
  {id:'Über uns',                de:'Über uns',                en:'About us',                    uk:'Про нас',              e:'🏢'},
  {id:'Kommunikation ist alles', de:'Kommunikation ist alles', en:'Communication is everything', uk:'Спілкування - це все', e:'💬'},
  {id:'Telefongespräch',         de:'Telefongespräch',         en:'Telephone conversation',      uk:'Телефонна розмова',    e:'📱'},
  {id:'Messe',                   de:'Messe',                   en:'Exhibition',                  uk:'Виставка',             e:'🎪'},
  {id:'Abkürzungen',             de:'Abkürzungen',             en:'Abbreviations',               uk:'Скорочення',           e:'✂️'}
];


const LC = {
  de: {code:'de-DE', ms:['Katja','Hedda','Stefan','Conrad']},
  en: {code:'en-US', ms:['Aria','Jenny','Guy','Zira','David']},
  uk: {code:'uk-UA', ms:['Ostap','Polina']}
};
const F  = {en:'🇬🇧', uk:'🇺🇦', de:'🇩🇪'};
const LN = {en:'English', uk:'Українська', de:'Deutsch'};


const VOCAB = [
{"id":"nvv_001","cat":"NVV","term":{"de":"sich in Acht nehmen vor","en":"to be wary of / to watch out for","uk":"остерігатися / бути обережним щодо чогось"},"short":{"de":"aufpassen, vorsichtig sein","en":"to be careful, cautious","uk":"бути уважним, обережним"},"def":{"de":"Vor komplizierten Verträgen sollte man sich in Acht nehmen.","en":"One should be wary of complicated contracts.","uk":"Слід бути обережним щодо складних договорів."}},
{"id":"nvv_002","cat":"NVV","term":{"de":"jemandem Achtung entgegenbringen","en":"to show respect to someone","uk":"виявляти повагу до когось"},"short":{"de":"jemanden achten, respektieren","en":"to respect, esteem someone","uk":"поважати, шанувати когось"},"def":{"de":"Es ist wichtig, auch der Konkurrenz Achtung entgegenzubringen.","en":"It is important to show respect even to the competition.","uk":"Важливо виявляти повагу навіть до конкурентів."}},
{"id":"nvv_003","cat":"NVV","term":{"de":"die Absicht haben zu","en":"to have the intention to / to intend to","uk":"мати намір / збиратися"},"short":{"de":"beabsichtigen","en":"to intend","uk":"мати намір"},"def":{"de":"Ich habe die Absicht, Karriere zu machen.","en":"I intend to build a career.","uk":"Я маю намір зробити кар'єру."}},
{"id":"nvv_004","cat":"NVV","term":{"de":"eine Änderung vornehmen","en":"to make a change","uk":"вносити зміну"},"short":{"de":"ändern","en":"to change","uk":"змінювати"},"def":{"de":"Alle Mitarbeitenden können an ihrem Passwort jederzeit eine Änderung vornehmen.","en":"All employees can make a change to their password at any time.","uk":"Усі співробітники можуть будь-коли змінити свій пароль."}},
{"id":"nvv_006","cat":"NVV","term":{"de":"eine Anforderung erfüllen","en":"to meet a requirement","uk":"відповідати вимозі / виконувати вимогу"},"short":{"de":"genügen","en":"to meet, satisfy","uk":"відповідати, задовольняти"},"def":{"de":"Sarina erfüllt alle Anforderungen in der Stellenausschreibung.","en":"Sarina meets all the requirements in the job posting.","uk":"Саріна відповідає всім вимогам оголошення про вакансію."}},

{"id":"ss_001","cat":"Soft Skills","term":{"de":"die Kommunikationsfähigkeit","en":"communication skills","uk":"комунікабельність"},"short":{"de":"sich klar ausdrücken","en":"expressing oneself clearly","uk":"вміння чітко висловлюватися"},"def":{"de":"Gut mit anderen sprechen und auch gut zuhören können.","en":"Being able to speak well with others and also listen well.","uk":"Вміння добре спілкуватися з іншими, а також уважно слухати."}},
{"id":"ss_002","cat":"Soft Skills","term":{"de":"die Teamfähigkeit","en":"ability to work in a team","uk":"вміння працювати в команді"},"short":{"de":"Kooperation mit Kollegen","en":"cooperation with colleagues","uk":"співпраця з колегами"},"def":{"de":"Gut und freundlich mit anderen Personen zusammenarbeiten.","en":"Working well and friendly with other people.","uk":"Добра та дружня співпраця з іншими людьми."}},
{"id":"ss_003","cat":"Soft Skills","term":{"de":"die Problemlösungskompetenz","en":"problem-solving skills","uk":"навичка вирішення проблем"},"short":{"de":"Lösungen finden","en":"finding solutions","uk":"пошук рішень"},"def":{"de":"Schwierige Situationen verstehen und schnell eine Lösung finden.","en":"Understanding difficult situations and finding a solution quickly.","uk":"Розуміння складних ситуацій та швидкий пошук рішення."}}
{"id":"ss_004","cat":"Soft Skills","term":{"de":"das Zeitmanagement","en":"time management","uk":"тайм-менеджмент"},"short":{"de":"Zeit effizient nutzen","en":"using time efficiently","uk":"ефективне використання часу"},"def":{"de":"Seine Zeit so planen, dass man alle Aufgaben pünktlich fertig macht.","en":"Planning your time so that you finish all tasks on time.","uk":"Планування свого часу так, щоб вчасно виконувати всі завдання."}},
{"id":"ss_005","cat":"Soft Skills","term":{"de":"die Anpassungsfähigkeit","en":"adaptability","uk":"адаптивність"},"short":{"de":"Flexibilität bei Veränderungen","en":"flexibility in changes","uk":"гнучкість при змінах"},"def":{"de":"Sich schnell an neue Regeln oder Situationen gewöhnen.","en":"Getting used to new rules or situations quickly.","uk":"Швидке звикання до нових правил або ситуацій."}},
{"id":"ss_006","cat":"Soft Skills","term":{"de":"die Kritikfähigkeit","en":"ability to take criticism","uk":"вміння сприймати критику"},"short":{"de":"Feedback annehmen","en":"accepting feedback","uk":"прийняття зворотного зв'язку"},"def":{"de":"Zuhören, wenn andere Fehler finden, і daraus lernen.","en":"Listening when others find mistakes and learning from it.","uk":"Вміння слухати, коли інші знаходять помилки, і вчитися на цьому."}},
{"id":"ss_007","cat":"Soft Skills","term":{"de":"das Einfühlungsvermögen","en":"empathy","uk":"емпатія"},"short":{"de":"Sichtweise anderer verstehen","en":"understanding others' views","uk":"розуміння поглядів інших"},"def":{"de":"Verstehen, як andere Menschen sich fühlen oder was sie denken.","en":"Understanding how other people feel or what they think.","uk":"Розуміння того, що відчувають або про що думають інші люди."}},
{"id":"ss_008","cat":"Soft Skills","term":{"de":"die Eigeninitiative","en":"self-initiative","uk":"проактивність / ініціативність"},"short":{"de":"selbst aktiv werden","en":"taking action independently","uk":"самостійна дія"},"def":{"de":"Selbst mit einer Arbeit anfangen, ohne dass der Chef es sagen muss.","en":"Starting work yourself without the boss having to say it.","uk":"Самостійний початок роботи без вказівки керівника."}},
{"id":"ss_009","cat":"Soft Skills","term":{"de":"die Belastbarkeit","en":"resilience / stress resistance","uk":"стресостійкість"},"short":{"de":"unter Druck arbeiten","en":"working under pressure","uk":"робота під тиском"},"def":{"de":"Ruhig bleiben, auch wenn es im Job sehr viel Stress gibt.","en":"Staying calm even when there is a lot of stress at work.","uk":"Збереження спокою, навіть якщо в роботі багато стресу."}},
{"id":"ss_010","cat":"Soft Skills","term":{"de":"die Konfliktfähigkeit","en":"conflict resolution skills","uk":"вміння вирішувати конфлікти"},"short":{"de":"Streit schlichten","en":"settling disputes","uk":"врегулювання суперечок"},"def":{"de":"Bei einem Streit ruhig bleiben і helfen, eine gute Lösung zu finden.","en":"Staying calm during an argument and helping to find a good solution.","uk":"Збереження спокою під час суперечки та допомога у пошуку доброго рішення."}},
{"id":"ss_011","cat":"Soft Skills","term":{"de":"das Projektmanagement","en":"project management","uk":"управління проектами"},"short":{"de":"Organisation von Aufgaben und Teams","en":"organization of tasks and teams","uk":"організація завдань та команд"},"def":{"de":"Eine Gruppe von Leuten und Aufgaben steuern, щоб ein Ziel erreicht wird.","en":"Managing a group of people and tasks so that a goal is reached.","uk":"Керування групою людей та завдань для досягнення мети."}},
{"id":"ss_012","cat":"Soft Skills","term":{"de":"Führung und Teamleistung","en":"leadership and team performance","uk":"лідерство та командна результативність"},"short":{"de":"Mitarbeiter motivieren und anleiten","en":"motivating and guiding employees","uk":"мотивація та керівництво працівниками"},"def":{"de":"Andere Menschen leiten і ihnen helfen, zusammen besser zu arbeiten.","en":"Leading other people and helping them work better together.","uk":"Керівництво іншими людьми та допомога їм краще працювати разом."}},
{"id":"ss_013","cat":"Soft Skills","term":{"de":"die Verhandlungskompetenz","en":"negotiation skills","uk":"навички ведення переговорів"},"short":{"de":"effektiver Austausch und Kompromissfindung","en":"effective exchange and finding compromises","uk":"ефективний обмін думками та пошук компромісів"},"def":{"de":"In einem Gespräch eine Lösung finden, die für beide Seiten gut ist.","en":"Finding a solution in a conversation that is good for both sides.","uk":"Пошук у розмові рішення, яке буде вигідним для обох сторін."}},
{"id":"ss_014","cat":"Soft Skills","term":{"de":"die Problemlösung","en":"problem solving","uk":"вирішення проблем"},"short":{"de":"Lösungen für Herausforderungen finden","en":"finding solutions to challenges","uk":"пошук рішень для викликів"},"def":{"de":"Einen Weg finden, um ein Hindernis oder eine Schwierigkeit zu beheben.","en":"Finding a way to fix an obstacle or a difficulty.","uk":"Пошук способу усунення перешкоди або труднощі."}},
{"id":"ss_015","cat":"Soft Skills","term":{"de":"die Lernbereitschaft","en":"willingness to learn","uk":"готовність до навчання"},"short":{"de":"neues Wissen erwerben wollen","en":"wanting to acquire new knowledge","uk":"бажання здобувати нові знання"},"def":{"de":"Interesse daran haben, immer wieder neue Dinge zu lernen.","en":"Having interest in learning new things again and again.","uk":"Інтерес до того, щоб постійно вивчати щось нове."}},
{"id":"ss_016","cat":"Soft Skills","term":{"de":"die Zuverlässigkeit","en":"reliability","uk":"надійність / пунктуальність"},"short":{"de":"getroffene Absprachen einhalten","en":"keeping made agreements","uk":"дотримання домовленостей"},"def":{"de":"Wenn andere Menschen wissen, dass man seine Aufgaben sicher macht.","en":"When other people know that you will surely do your tasks.","uk":"Коли інші люди знають, що ви точно виконаєте свої завдання."}},
{"id":"ss_017","cat":"Soft Skills","term":{"de":"das Durchsetzungsvermögen","en":"assertiveness","uk":"вміння наполягати на своєму"},"short":{"de":"eigene Ziele erreichen","en":"achieving own goals","uk":"досягнення власних цілей"},"def":{"de":"Seine Meinung oder Ziele gegen Widerstand freundlich aber fest vertreten.","en":"Representing your opinion or goals kindly but firmly against resistance.","uk":"Дружнє, але тверде відстоювання своєї думки чи цілей попри опір."}},
{"id":"ss_018","cat":"Soft Skills","term":{"de":"die Zielorientierung","en":"goal orientation","uk":"цілеспрямованість"},"short":{"de":"fokussiert auf Ergebnisse arbeiten","en":"working focused on results","uk":"фокусування на результаті"},"def":{"de":"Sich nicht ablenken lassen і direkt am Erfolg arbeiten.","en":"Not getting distracted and working directly for success.","uk":"Вміння не відволікатися і працювати безпосередньо на результат."}},
{"id":"ss_019","cat":"Soft Skills","term":{"de":"das vernetzte Denken","en":"interdisciplinary thinking","uk":"системне мислення"},"short":{"de":"Zusammenhänge erkennen","en":"recognizing connections","uk":"розуміння взаємозв'язків"},"def":{"de":"Verstehen, як verschiedene Themen in der Firma zusammengehören.","en":"Understanding how different topics in the company belong together.","uk":"Розуміння того, як різні теми в компанії пов'язані між собою."}},
{"id":"ss_020","cat":"Soft Skills","term":{"de":"die Selbstständigkeit","en":"independence","uk":"самостійність"},"short":{"de":"ohne Hilfe arbeiten","en":"working without help","uk":"робота без допомоги"},"def":{"de":"Aufgaben alleine planen und ohne ständige Kontrolle erledigen.","en":"Planning tasks alone and completing them without constant control.","uk":"Самостійне планування завдань та їх виконання без постійного контролю."}},
{"id":"ss_021","cat":"Soft Skills","term":{"de":"die Motivationsfähigkeit","en":"ability to motivate","uk":"вміння мотивувати"},"short":{"de":"andere begeistern können","en":"being able to inspire others","uk":"вміння надихати інших"},"def":{"de":"Andere Leute dazu bringen, що sie ihre Arbeit mit Freude machen.","en":"Getting other people to do their work with joy.","uk":"Вміння заохотити інших людей виконувати роботу з радістю."}},
{"id":"ss_022","cat":"Soft Skills","term":{"de":"die interkulturelle Kompetenz","en":"intercultural competence","uk":"міжкультурна компетенція"},"short":{"de":"Umgang mit anderen Kulturen","en":"dealing with other cultures","uk":"взаємодія з іншими культурами"},"def":{"de":"Gut mit Menschen aus verschiedenen Ländern zusammenarbeiten.","en":"Working well with people from different countries.","uk":"Добра співпраця з людьми з різних країн."}},
{"id":"ss_023","cat":"Soft Skills","term":{"de":"die Präsentationsstärke","en":"presentation skills","uk":"навички презентації"},"short":{"de":"Ideen gut vorstellen","en":"presenting ideas well","uk":"вміння гарно презентувати ідеї"},"def":{"de":"Informationen vor einer Gruppe sicher und interessant zeigen.","en":"Showing information to a group confidently and interestingly.","uk":"Впевнене та цікаве представлення інформації перед групою."}},
{"id":"ss_024","cat":"Soft Skills","term":{"de":"die Überzeugungskraft","en":"persuasiveness","uk":"переконливість"},"short":{"de":"andere von einer Idee überzeugen","en":"convincing others of an idea","uk":"вміння переконати інших в ідеї"},"def":{"de":"Gute Argumente finden, damit andere Menschen einem zustimmen.","en":"Finding good arguments so that other people agree with you.","uk":"Пошук хороших аргументів, щоб інші люди з вами погодилися."}},
{"id":"ss_025","cat":"Soft Skills","term":{"de":"die Diskretion","en":"discretion","uk":"дискретність / стриманість"},"short":{"de":"Geheimnisse bewahren","en":"keeping secrets","uk":"збереження таємниць"},"def":{"de":"Wichtige Informationen für sich behalten und nicht weitererzählen.","en":"Keeping important information to oneself and not telling others.","uk":"Збереження важливої інформації при собі та нерозголошення її іншим."}},

];
